/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class assistantUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("assistant");
        }
    }
    export class CardUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public cardItem:Laya.Image;
		public sceneImg:Laya.Image;
		public goodsName:Laya.Label;
		public award:Laya.Label;
		public progress:Laya.ProgressBar;
		public soldNum_totalNum:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Card");
        }
    }
    export class grandPrixUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("grandPrix");
        }
    }
    export class guessingUI extends Laya.Scene {
		public price:Laya.Label;
		public goodsValue:Laya.Label;
		public progressSpeed:Laya.ProgressBar;
		public soldNum_soldNum:Laya.Label;
		public period:Laya.Label;
		public numberList:Laya.List;
		public total:Laya.Label;
		public balance:Laya.Label;
		public btn_buy:Laya.Image;
		public btn_select:Laya.View;
		public random_one:Laya.Label;
		public random_before:Laya.Label;
		public random_after:Laya.Label;
		public random_all:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("guessing");
        }
    }
    export class homeUI extends Laya.Scene {
		public put_in:Laya.FrameAnimation;
		public rocket_show:Laya.FrameAnimation;
		public dom_show:Laya.FrameAnimation;
		public bg_ani:Laya.FrameAnimation;
		public bg_animation:Laya.Sprite;
		public tuichu:Laya.Image;
		public AccountBox:Laya.Image;
		public avatar:Laya.Image;
		public nickName:Laya.Label;
		public rechargeBox:Laya.Image;
		public btnRecharge:Laya.Image;
		public myAmount:Laya.Label;
		public putin:Laya.Sprite;
		public rockerBox:Laya.Sprite;
		public countDown:Laya.Sprite;
		public rocketAmount:Laya.Label;
		public rocketCountDown:Laya.Label;
		public list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home");
        }
    }
    export class recordUI extends Laya.Scene {
		public canyu:Laya.Image;
		public wangqi:Laya.Image;
		public previoousList:Laya.List;
		public joinList:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("record");
        }
    }
    export class TabbarUI extends Laya.View {
		public tab:Laya.Tab;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Tabbar");
        }
    }
}
export module ui.template {
    export class InputPwdDialogUI extends Laya.Dialog {
		public title:Laya.Label;
		public btnClose:Laya.Box;
		public IptPsw:Laya.TextInput;
		public forgetPassword:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("template/InputPwdDialog");
        }
    }
    export class joinRecordsUI extends Laya.View {
		public noPrize:Laya.Label;
		public prize:Laya.Image;
		public prize_number:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("template/joinRecords");
        }
    }
    export class numberListDOMUI extends Laya.View {
		public bgImg:Laya.Image;
		public code:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("template/numberListDOM");
        }
    }
    export class previousRecordsUI extends Laya.View {
		public number:Laya.Label;
		public lotteryType:Laya.Label;
		public hash:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("template/previousRecords");
        }
    }
    export class TipsDialogUI extends Laya.Dialog {
		public title:Laya.Label;
		public btnViewRecord:Laya.Image;
		public btnContinue:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("template/TipsDialog");
        }
    }
    export class ToastUI extends Laya.View {
		public text_label:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("template/Toast");
        }
    }
}