/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Assistant from "./script/Assistant"
import PageScript from "./publicScript/PageScript"
import Screen from "./publicScript/Screen"
import trendList from "./template/trendList"
import previousRecords from "./template/previousRecords"
import Card from "./script/Card"
import grandPrix from "./script/grandPrix"
import PageNavScript from "./publicScript/PageNavScript"
import prixList from "./template/prixList"
import Guessing from "./script/Guessing"
import numberListDomScript from "./template/numberListDomScript"
import Home from "./script/Home"
import priHistoryScene from "./script/priHistoryScene"
import priHistory from "./template/priHistory"
import Record from "./script/Record"
import joinRecords from "./template/joinRecords"
import pswInput from "./template/pswInput"
import tipDialog from "./template/tipDialog"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="home.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Assistant.ts",Assistant);
        reg("publicScript/PageScript.ts",PageScript);
        reg("publicScript/Screen.ts",Screen);
        reg("template/trendList.ts",trendList);
        reg("template/previousRecords.ts",previousRecords);
        reg("script/Card.ts",Card);
        reg("script/grandPrix.ts",grandPrix);
        reg("publicScript/PageNavScript.ts",PageNavScript);
        reg("template/prixList.ts",prixList);
        reg("script/Guessing.ts",Guessing);
        reg("template/numberListDomScript.ts",numberListDomScript);
        reg("script/Home.ts",Home);
        reg("script/priHistoryScene.ts",priHistoryScene);
        reg("template/priHistory.ts",priHistory);
        reg("script/Record.ts",Record);
        reg("template/joinRecords.ts",joinRecords);
        reg("template/pswInput.ts",pswInput);
        reg("template/tipDialog.ts",tipDialog);
    }
}
GameConfig.init();